services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Service
    eikona_media.contao.system_information_service:
        class: EikonaMedia\Contao\SystemInformation\Service\SystemInformationService

    # Controller
    EikonaMedia\Contao\SystemInformation\Controller\BackendController:
        arguments:
            - '@eikona_media.contao.system_information_service'
            - '@request_stack'
            - '@router'
            - '@translator'
            - '@contao.framework'
            - '@twig'
