services:
    _defaults:
        autowire: true
        autoconfigure: true

    EikonaMedia\Contao\SystemInformation\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection}'

    eikona_media.contao.system_information_service:
        alias: EikonaMedia\Contao\SystemInformation\Service\SystemInformationService
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'
